// Registry of interactive widgets. A widget can be a lab (a full simulator
// with its own page under /labs), a visualization (embeddable in lessons and
// listed under /visualizations), or both. Plain data, safe on server and client.
import type { SubjectId } from "@/lib/content/types";

export type WidgetKind = "lab" | "viz";

export interface WidgetDef {
  id: string;
  title: string;
  subject: Exclude<SubjectId, "x">;
  kinds: WidgetKind[];
  description: string;
  /** What the learner should try — shown above the widget on its own page. */
  tryThis: string[];
  lessons: string[];
}

export const WIDGETS: WidgetDef[] = [
  // ───────────────────────────── Operating Systems ─────────────────────────────
  {
    id: "process-lifecycle",
    title: "Process Lifecycle State Machine",
    subject: "os",
    kinds: ["viz", "lab"],
    description: "Drive a process through new → ready → running → blocked → terminated and watch which transitions the kernel allows, and why.",
    tryThis: ["Try to move a Ready process directly to Blocked — why is that impossible?", "Exit a child before the parent calls wait(): observe the zombie.", "Kill the parent of a running child: observe re-parenting (orphan)."],
    lessons: ["os-processes", "os-process-creation"],
  },
  {
    id: "context-switch",
    title: "Context Switch, Step by Step",
    subject: "os",
    kinds: ["viz"],
    description: "Follow a timer interrupt through register saving, PCB updates, scheduler choice, address-space switch and resumption.",
    tryThis: ["Compare a thread switch within a process to a process switch — which steps disappear?", "Note where the TLB and caches get cold."],
    lessons: ["os-context-switch", "os-threads"],
  },
  {
    id: "race-condition",
    title: "Race Condition Interleavings",
    subject: "os",
    kinds: ["viz", "lab"],
    description: "Two threads execute counter++ as LOAD / ADD / STORE. Choose the interleaving and watch updates get lost — then add a lock.",
    tryThis: ["Find an interleaving that loses an update.", "Enable the mutex: which interleavings become impossible?", "How many total interleavings exist for two threads of three instructions?"],
    lessons: ["os-race-conditions", "os-sync-primitives", "os-critical-section-problem"],
  },
  {
    id: "cpu-scheduler",
    title: "CPU Scheduling Simulator",
    subject: "os",
    kinds: ["lab", "viz"],
    description: "Enter processes with arrival, burst and priority. Compare FCFS, SJF, SRTF, Round Robin, Priority and MLFQ with Gantt charts and per-process metrics.",
    tryThis: ["Put one long job first: see the convoy effect under FCFS.", "Shrink the RR quantum to 1 and count context switches.", "Give one process low priority and many high-priority arrivals: watch starvation, then enable aging."],
    lessons: ["os-scheduling-basics", "os-scheduling-algorithms", "os-mlfq-real-schedulers"],
  },
  {
    id: "address-translation",
    title: "Address Translation: TLB & Page Tables",
    subject: "os",
    kinds: ["viz", "lab"],
    description: "Split a virtual address into page number and offset, check the TLB, walk a two-level page table and produce a physical address — or a page fault.",
    tryThis: ["Access the same page twice: the second is a TLB hit.", "Access an unmapped page: see the fault path.", "Change the page size and watch the bit split move."],
    lessons: ["os-paging", "os-tlb", "os-page-faults"],
  },
  {
    id: "page-replacement",
    title: "Page Replacement Simulator",
    subject: "os",
    kinds: ["lab", "viz"],
    description: "Run FIFO, Optimal, LRU and Clock over any reference string and frame count. Step through every fault and eviction.",
    tryThis: ["Reference string 1 2 3 4 1 2 5 1 2 3 4 5 with 3 then 4 frames under FIFO: Belady's anomaly.", "Compare LRU and Clock on a looping pattern larger than memory."],
    lessons: ["os-page-replacement", "os-thrashing-working-set"],
  },
  {
    id: "memory-allocator",
    title: "Memory Allocation Simulator",
    subject: "os",
    kinds: ["lab"],
    description: "Allocate and free blocks with first-fit, best-fit, worst-fit and next-fit. Watch external fragmentation appear.",
    tryThis: ["Allocate A,B,C,D then free B and D: can a request larger than each hole succeed?", "Compare how many requests each policy satisfies on the same trace."],
    lessons: ["os-dynamic-allocation"],
  },
  {
    id: "bankers",
    title: "Banker's Algorithm & Deadlock Detection",
    subject: "os",
    kinds: ["lab"],
    description: "Edit Allocation, Max and Available matrices. Run the safety algorithm step by step, evaluate requests, and detect deadlock.",
    tryThis: ["Find the safe sequence for the textbook example.", "Make a request that is valid but unsafe — the algorithm refuses it.", "Switch to detection mode and create a deadlocked set."],
    lessons: ["os-deadlock-handling", "os-deadlocks"],
  },
  {
    id: "deadlock-graph",
    title: "Resource-Allocation Graph",
    subject: "os",
    kinds: ["viz"],
    description: "Add request and assignment edges between threads and locks. The graph highlights cycles — and explains when a cycle is (and isn't) a deadlock.",
    tryThis: ["Build the classic two-lock deadlock.", "Add a second instance of a resource: the cycle no longer guarantees deadlock."],
    lessons: ["os-deadlocks"],
  },
  {
    id: "producer-consumer",
    title: "Producer–Consumer with Semaphores",
    subject: "os",
    kinds: ["lab", "viz"],
    description: "Step producers and consumers over a bounded buffer guarded by empty, full and mutex semaphores. Break the protocol and watch it deadlock or corrupt.",
    tryThis: ["Fill the buffer: which thread blocks, on which semaphore?", "Enable 'wrong wait order' and find the deadlock.", "Remove the mutex and create a lost item."],
    lessons: ["os-classic-sync-problems", "os-semaphores-monitors"],
  },
  {
    id: "disk-scheduling",
    title: "Disk Scheduling",
    subject: "os",
    kinds: ["lab"],
    description: "Compare FCFS, SSTF, SCAN, C-SCAN, LOOK and C-LOOK head movement for a request queue.",
    tryThis: ["Find a queue where SSTF starves a far request.", "Why is total head movement irrelevant for an SSD?"],
    lessons: ["os-storage-devices"],
  },
  {
    id: "io-models",
    title: "I/O Models Timeline",
    subject: "os",
    kinds: ["viz"],
    description: "Blocking, non-blocking polling, I/O multiplexing (epoll) and async I/O side by side: who waits, where, and how many threads it costs.",
    tryThis: ["Increase concurrent connections: watch thread count per model.", "Where does the data copy from kernel to user space happen in each model?"],
    lessons: ["os-io-models", "os-epoll-event-loops"],
  },
  // ───────────────────────────── Computer Networks ─────────────────────────────
  {
    id: "encapsulation",
    title: "Encapsulation Through the Stack",
    subject: "cn",
    kinds: ["viz"],
    description: "Watch an HTTP request gain a TCP header, an IP header and an Ethernet frame — then cross a router, which rewrites only what it must.",
    tryThis: ["At the router, which headers change and which do not?", "Where would TLS encryption sit in this picture?"],
    lessons: ["cn-encapsulation", "cn-layered-models", "cn-how-data-travels"],
  },
  {
    id: "tcp-handshake",
    title: "TCP Connection Simulator",
    subject: "cn",
    kinds: ["lab", "viz"],
    description: "Open, use and close a TCP connection. Watch sequence and acknowledgement numbers, both endpoints' states, and what happens when a segment is lost.",
    tryThis: ["Drop the SYN-ACK: who retransmits, and when?", "Close from the client: find TIME_WAIT and explain who holds it.", "Send data and verify that ACK = next byte expected."],
    lessons: ["cn-tcp-handshake", "cn-tcp-reliability", "cn-tcp-termination"],
  },
  {
    id: "sliding-window",
    title: "Sliding Window & Flow Control",
    subject: "cn",
    kinds: ["viz", "lab"],
    description: "A sender's byte stream partitioned into acked, in-flight, sendable and not-yet-allowed. Shrink the receiver window, lose a segment, and watch the window move.",
    tryThis: ["Set “App reads / round” to 0: what happens to rwnd and to the sender?", "Lose segment 3: observe out-of-order buffering, duplicate ACKs and fast retransmit.", "Make cwnd smaller than the buffer: which limit is binding now?"],
    lessons: ["cn-tcp-flow-control", "cn-tcp-reliability"],
  },
  {
    id: "congestion",
    title: "Congestion Window Over Time",
    subject: "cn",
    kinds: ["viz", "lab"],
    description: "Plot cwnd per RTT through slow start, congestion avoidance, timeouts and triple-duplicate-ACK losses under Tahoe and Reno.",
    tryThis: ["Inject a timeout vs a triple-dup-ACK loss at the same RTT: compare recovery.", "Where does ssthresh come from after each loss?"],
    lessons: ["cn-tcp-congestion-control"],
  },
  {
    id: "dns-resolver",
    title: "DNS Resolution Simulator",
    subject: "cn",
    kinds: ["lab", "viz"],
    description: "Resolve names through a recursive resolver: root, TLD and authoritative servers, CNAME chains, caching and TTL expiry.",
    tryThis: ["Resolve twice: the second lookup is served from cache.", "Advance the clock past the TTL.", "Resolve a name that is a CNAME to a CDN."],
    lessons: ["cn-dns-fundamentals", "cn-dns-records"],
  },
  {
    id: "tls-handshake",
    title: "TLS 1.3 Handshake",
    subject: "cn",
    kinds: ["viz"],
    description: "Message by message: key shares, the certificate, CertificateVerify, Finished — what is encrypted when, and where the keys come from. Compare with TLS 1.2.",
    tryThis: ["Count round trips before application data in 1.3 vs 1.2.", "Which message proves the server holds the private key?"],
    lessons: ["cn-tls-handshake", "cn-certificates-pki", "cn-crypto-foundations"],
  },
  {
    id: "subnet-calculator",
    title: "Subnet Calculator & Trainer",
    subject: "cn",
    kinds: ["lab"],
    description: "Compute network, broadcast, mask, host range and host count for any CIDR — in binary — and practice with generated subnetting problems.",
    tryThis: ["Compare /24, /26 and /30.", "Split 10.0.0.0/22 into four equal subnets.", "Use practice mode until you can do it without the calculator."],
    lessons: ["cn-subnetting", "cn-ipv4-addressing"],
  },
  {
    id: "routing",
    title: "Packet Routing Simulator",
    subject: "cn",
    kinds: ["lab", "viz"],
    description: "Send a packet across a small network of routers. Each hop does a longest-prefix match, decrements TTL and re-frames the packet; the edge router performs NAT.",
    tryThis: ["Send to 172.16.5.5 (no route): which router replies with ICMP, and why that one?", "Set TTL=2, then run traceroute mode.", "Watch the source address/port change at R1's NAT.", "Send to 203.0.113.99: how does “host unreachable” differ from “network unreachable”?"],
    lessons: ["cn-routing", "cn-nat", "cn-ip-packet-icmp"],
  },
  {
    id: "http-cache",
    title: "HTTP Caching Simulator",
    subject: "cn",
    kinds: ["lab"],
    description: "Configure Cache-Control and validators, advance the clock, and see whether each request is served fresh, revalidated with a 304, or fetched again.",
    tryThis: ["Compare no-cache and no-store.", "Set max-age=60 with an ETag and request at t=30, t=90.", "Change the resource at the origin: what does a stale cache serve?"],
    lessons: ["cn-http-caching", "cn-cdn"],
  },
  {
    id: "realtime-transports",
    title: "Polling vs Long Polling vs SSE vs WebSockets",
    subject: "cn",
    kinds: ["viz"],
    description: "The same stream of server events delivered four ways, with request counts, header overhead and delivery latency side by side.",
    tryThis: ["Increase the polling interval: latency vs request count.", "Why does SSE not help for client→server messages?"],
    lessons: ["cn-realtime"],
  },
  {
    id: "network-calculator",
    title: "Latency, Bandwidth & Throughput Calculator",
    subject: "cn",
    kinds: ["lab"],
    description: "Transfer time, bandwidth-delay product, window-limited TCP throughput and the Mathis loss bound — computed and explained.",
    tryThis: ["Why does a 1 GB file over a 10 Gbps link with 100 ms RTT not finish in 0.8 s?", "How big must the window be to fill a 1 Gbps × 80 ms path?"],
    lessons: ["cn-latency-bandwidth", "cn-tcp-flow-control", "cn-tail-latency"],
  },
  {
    id: "hol-blocking",
    title: "Head-of-Line Blocking: HTTP/1.1 vs HTTP/2 vs HTTP/3",
    subject: "cn",
    kinds: ["viz"],
    description: "Three responses, one lost packet. See which responses stall under HTTP/1.1, HTTP/2 over TCP, and HTTP/3 over QUIC.",
    tryThis: ["Lose A2: which streams wait in each protocol?", "Pick “no loss”: why does HTTP/2 finish A later than serialized HTTP/1.1?", "Lose C4 (the last packet): does HTTP/2 still hurt anyone?"],
    lessons: ["cn-http2", "cn-http3-quic", "cn-tcp-reliability"],
  },
  // ───────────────────────────── Databases ─────────────────────────────
  {
    id: "sql-playground",
    title: "SQL Playground (real PostgreSQL)",
    subject: "db",
    kinds: ["lab"],
    description: "A real PostgreSQL running in your browser via WebAssembly, preloaded with a realistic schema and graded exercises from basic SELECT to window functions.",
    tryThis: ["Work through the graded exercises in order.", "Break a query on purpose: NOT IN with a NULL.", "Reset the database whenever you like."],
    lessons: ["sql-select-basics", "sql-joins", "sql-window-functions", "sql-interview-patterns"],
  },
  {
    id: "query-plan",
    title: "Query Plan Visualizer",
    subject: "db",
    kinds: ["lab"],
    description: "Run EXPLAIN ANALYZE on real PostgreSQL, rendered as a plan tree with estimated vs actual rows. Create and drop indexes and watch the planner change its mind.",
    tryThis: ["Run the lookup query, add the suggested index, run again.", "Find a query where the planner prefers a sequential scan despite an index.", "Compare a hash join with a nested loop by changing selectivity."],
    lessons: ["db-explain", "db-scans-joins", "db-query-optimization", "db-index-fundamentals"],
  },
  {
    id: "btree",
    title: "B+ Tree Visualizer",
    subject: "db",
    kinds: ["lab", "viz"],
    description: "Insert, search and range-scan a B+ tree of configurable order. Watch leaf and internal splits propagate and count page reads per lookup.",
    tryThis: ["Insert 1..20 in order with order 4: observe right-heavy splits.", "Search for a key and count node visits.", "Range scan 5..12: why are leaves linked?"],
    lessons: ["db-btree", "db-index-fundamentals"],
  },
  {
    id: "sql-joins",
    title: "Join Types, Row by Row",
    subject: "db",
    kinds: ["viz"],
    description: "Two small tables and every join type — inner, left, right, full, cross, semi, anti — with each output row traced back to its source rows.",
    tryThis: ["Add a duplicate key on the right: watch the join multiply rows.", "Add a NULL key: which joins keep it?"],
    lessons: ["sql-joins", "sql-semi-anti-joins"],
  },
  {
    id: "join-algorithms",
    title: "Join Algorithms: Nested Loop vs Hash vs Merge",
    subject: "db",
    kinds: ["viz"],
    description: "Step through the three physical join algorithms on the same data with comparison and memory counters.",
    tryThis: ["Grow the outer table: which algorithm degrades fastest?", "When is merge join free?"],
    lessons: ["db-scans-joins"],
  },
  {
    id: "isolation",
    title: "Transaction Isolation Simulator (MVCC)",
    subject: "db",
    kinds: ["lab", "viz"],
    description: "Two concurrent transactions, a versioned row store and an isolation level. Step through classic anomalies and see exactly which version each read returns.",
    tryThis: ["Run 'lost update' under Read Committed, then Repeatable Read.", "Run 'write skew' under Repeatable Read — then Serializable.", "Watch xmin/xmax on each row version."],
    lessons: ["db-anomalies", "db-isolation-levels", "db-mvcc"],
  },
  {
    id: "db-locks",
    title: "Lock Manager & Deadlock Simulator",
    subject: "db",
    kinds: ["lab"],
    description: "Transactions request shared and exclusive row locks. See the lock table, wait queues and the wait-for graph — and which transaction the detector kills.",
    tryThis: ["Two readers share; a writer waits.", "Build a deadlock by locking rows in opposite order.", "Fix it with consistent lock ordering."],
    lessons: ["db-locking", "os-deadlocks"],
  },
  {
    id: "wal-recovery",
    title: "WAL & Crash Recovery Simulator",
    subject: "db",
    kinds: ["lab"],
    description: "Execute transactions against a buffer pool and write-ahead log. Checkpoint, flush pages, then crash at any moment and run redo/undo recovery.",
    tryThis: ["Crash right after COMMIT before any data page is written.", "Crash with a dirty page from an uncommitted transaction on disk (steal).", "Checkpoint, then crash: how much log does recovery scan?"],
    lessons: ["db-crash-recovery", "db-wal-durability", "db-buffer-pool"],
  },
  {
    id: "replication",
    title: "Replication & Failover Simulator",
    subject: "db",
    kinds: ["lab"],
    description: "A primary and two replicas with adjustable lag. Toggle synchronous replication, read from replicas, kill the primary and promote — watch lost writes and split brain.",
    tryThis: ["Write then immediately read from a lagging replica.", "Kill the primary with async replication: which writes are lost?", "Partition the old primary without fencing."],
    lessons: ["db-replication", "db-failover"],
  },
  {
    id: "consistent-hashing",
    title: "Consistent Hashing & Sharding",
    subject: "db",
    kinds: ["lab", "viz"],
    description: "Place keys on a hash ring with virtual nodes. Add and remove nodes and measure how many keys move — compared with hash mod N.",
    tryThis: ["Add a 4th node with mod-N hashing vs the ring.", "Set virtual nodes to 1, then 100: look at load balance.", "Create a hot key."],
    lessons: ["db-consistent-hashing", "db-sharding"],
  },
  {
    id: "quorum",
    title: "Quorum Overlap",
    subject: "db",
    kinds: ["viz"],
    description: "Choose N, W and R and see which write and read sets can fail to overlap — and what that means for stale reads.",
    tryThis: ["N=3, W=2, R=2 vs W=1, R=1.", "Is R+W>N enough for linearizability? Read the caveats."],
    lessons: ["db-quorums-consensus", "db-wide-column"],
  },
  {
    id: "lsm",
    title: "LSM Tree: Memtable, SSTables & Compaction",
    subject: "db",
    kinds: ["viz", "lab"],
    description: "Writes go to a memtable, flush to immutable SSTables and get compacted. Reads check bloom filters level by level.",
    tryThis: ["Overwrite one key many times, then compact.", "Read a missing key: how many SSTables are skipped thanks to bloom filters?", "Delete a key: see the tombstone."],
    lessons: ["db-lsm-trees"],
  },
  {
    id: "normalization",
    title: "Functional Dependency & Normal Form Analyzer",
    subject: "db",
    kinds: ["lab"],
    description: "Enter a relation and its functional dependencies. Compute attribute closures, candidate keys, the highest normal form and a BCNF decomposition.",
    tryThis: ["Load the student-course example and find why it is not 2NF.", "Decompose to BCNF and check which dependency is lost."],
    lessons: ["db-functional-dependencies", "db-normalization"],
  },
];

export const WIDGET_IDS = new Set(WIDGETS.map((w) => w.id));

export function getWidget(id: string): WidgetDef | undefined {
  return WIDGETS.find((w) => w.id === id);
}
